#!/usr/bin/env bash
set -euo pipefail
rm -rf dist
mkdir -p dist
echo "Transpiling index.ls to index.named.js..."
./node_modules/.bin/lsc -cp --no-header src/index.ls > dist/index.named.js

echo "Transpiling index.ls without name list..."
cat src/index.ls | grep -v "named = " | lsc -csp --no-header > dist/index.js
echo "Uglify index.named.js...."
./node_modules/.bin/uglifyjs dist/index.named.js -m -c > dist/index.named.min.js
echo "Uglify index.js...."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
