#!/usr/bin/env bash

mkdir -p dist
rm dist/*.js
echo "Transpiling ldColor.ls to ldColor.named.js..."
lsc -cpb src/main.ls > dist/ldColor.named.js

echo "Transpiling ldColor.ls without name list..."
cat src/main.ls | grep -v "named = " | lsc -cbsp > dist/ldColor.js
echo "Uglify ldColor.named.js...."
uglifyjs dist/ldColor.named.js > dist/ldColor.named.min.js
echo "Uglify ldColor.js...."
uglifyjs dist/ldColor.js > dist/ldColor.min.js
